// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {guard} from '../models';
import {license} from '../models';
import {maintenance} from '../models';
import {main} from '../models';
import {app} from '../models';
import {messagepush} from '../models';
import {farm} from '../models';
import {automation} from '../models';
import {storage} from '../models';
import {social} from '../models';
import {qqpatch} from '../models';
import {diagnostics} from '../models';
import {eventbus} from '../models';
import {runtime} from '../models';

export function AutoBindHostProcess():Promise<guard.AutoBindOwnerResult>;

export function BindHostProcess(arg1:number):Promise<guard.HostBinding>;

export function CheckForUpdates():Promise<license.UpdateState>;

export function CleanQQMiniappCache():Promise<maintenance.Summary>;

export function CleanWeChatCache():Promise<maintenance.Summary>;

export function CleanYYBMiniappCache():Promise<maintenance.Summary>;

export function ClearHostBinding():Promise<boolean>;

export function ConfirmRuntimeAccount(arg1:main.RuntimeAccount):Promise<main.RuntimeAccount>;

export function ConnectionInfo():Promise<app.ConnectionInfo>;

export function CurrentRuntimeAccount():Promise<main.RuntimeAccount>;

export function DefaultMessagePushTemplate(arg1:string,arg2:string):Promise<messagepush.Template>;

export function ExitApplication():Promise<void>;

export function ExportRuntimeLogs(arg1:string):Promise<main.SaveTextFileResult>;

export function FarmAccountStatus():Promise<farm.AccountStatusPayload>;

export function FarmAtlasBuyLockedCrops(arg1:Record<string, any>):Promise<farm.AtlasPurchasePayload>;

export function FarmAtlasBuyLockedPreview(arg1:Record<string, any>):Promise<farm.AtlasPurchasePreviewPayload>;

export function FarmAtlasPreview():Promise<farm.AtlasPreviewPayload>;

export function FarmAutomationSchedulerState():Promise<automation.SchedulerState>;

export function FarmAutomationState():Promise<automation.State>;

export function FarmBackpackSeedOptions(arg1:Record<string, any>):Promise<farm.BackpackSeedOptionsPayload>;

export function FarmCropAnalytics():Promise<farm.CropAnalyticsPayload>;

export function FarmFeatureCatalog():Promise<farm.FeatureCatalog>;

export function FarmFertilizeLand(arg1:Record<string, any>):Promise<Record<string, any>>;

export function FarmLandDetails():Promise<farm.LandDetailsPayload>;

export function FarmLandDetailsSince(arg1:string):Promise<farm.LandDetailsDeltaPayload>;

export function FarmLandRush(arg1:Record<string, any>):Promise<Record<string, any>>;

export function FarmMysteryShopPurchaseRecords():Promise<Array<storage.MysteryShopPurchaseRecord>>;

export function FarmShovelLands(arg1:Record<string, any>):Promise<Record<string, any>>;

export function FarmSocialAction(arg1:social.FriendActionRequest):Promise<social.ActionResult>;

export function FarmSocialDogGuardAction(arg1:social.DogGuardActionRequest):Promise<social.DogGuardState>;

export function FarmSocialDogGuardState():Promise<social.DogGuardState>;

export function FarmSocialExport(arg1:social.ExportRequest):Promise<social.ImportExportPayload>;

export function FarmSocialImport(arg1:social.ImportExportPayload):Promise<social.ActionResult>;

export function FarmSocialProtocolBlockList(arg1:boolean):Promise<social.ProtocolBlockList>;

export function FarmSocialRankingPreferences():Promise<social.RankingPreferences>;

export function FarmSocialRankings(arg1:social.RankingRequest):Promise<social.RankingPage>;

export function FarmSocialRefreshVisitors():Promise<social.ActionResult>;

export function FarmSocialState(arg1:boolean):Promise<social.State>;

export function FarmStealCropOptions():Promise<farm.StealCropOptionsPayload>;

export function FarmWarehouse():Promise<farm.WarehousePayload>;

export function FarmWarehouseRefresh():Promise<farm.WarehousePayload>;

export function FarmWarehouseSell(arg1:Record<string, any>):Promise<farm.WarehouseSellPayload>;

export function FarmWarehouseSellRecords(arg1:Record<string, any>):Promise<Array<storage.WarehouseSellRecord>>;

export function FarmWorkspaceRunStatistics():Promise<farm.RunStatistics>;

export function GetProgramNotice():Promise<license.ProgramNotice>;

export function GuardianStatus():Promise<main.GuardianStatusDTO>;

export function IdentifyRuntimeAccount():Promise<main.RuntimeAccount>;

export function InstallQQDebugPatch(arg1:string):Promise<qqpatch.Result>;

export function LANAccessSettings():Promise<main.LANAccessStatus>;

export function LaunchHostProcess():Promise<guard.HostLaunchResult>;

export function ListHostCandidates():Promise<Array<guard.HostProcessCandidate>>;

export function MessagePushState():Promise<messagepush.ViewState>;

export function MinimizeToTray():Promise<void>;

export function PreviewHostRestart():Promise<guard.HostRestartPreview>;

export function PreviewMessagePushTemplate(arg1:messagepush.Config,arg2:string,arg3:string):Promise<messagepush.TemplatePreview>;

export function PreviewWeChatCacheCleanup():Promise<maintenance.Summary>;

export function ProcessGuardStatus():Promise<guard.Status>;

export function QQDebugPatchStatus():Promise<main.QQDebugPatchStatus>;

export function RestartHostProcess():Promise<guard.RestartResult>;

export function RunDiagnostic(arg1:string,arg2:Record<string, any>):Promise<diagnostics.Result>;

export function RunDueFarmAutomationTasks():Promise<automation.SchedulerState>;

export function RunDueMessagePushDaily():Promise<messagepush.SendResult>;

export function RunFarmAutomationTask(arg1:string):Promise<automation.ActionResult>;

export function RunGuardianAction(arg1:guard.ActionRequest):Promise<guard.ActionResult>;

export function RunScheduledFarmAutomationTask(arg1:string):Promise<automation.ActionResult>;

export function RuntimeEvents(arg1:number):Promise<Array<eventbus.Event>>;

export function RuntimeLinkStatus():Promise<runtime.Status>;

export function RuntimeSettings():Promise<storage.RuntimeSettings>;

export function RuntimeStatus():Promise<runtime.Status>;

export function SaveFarmAutomationState(arg1:automation.State):Promise<automation.State>;

export function SaveFarmSocialRankingPreferences(arg1:string,arg2:social.RankingPreferences):Promise<social.RankingPreferences>;

export function SaveGuardianSettings(arg1:Record<string, any>):Promise<guard.Settings>;

export function SaveLANAccessSettings(arg1:main.LANAccessSettingsInput):Promise<main.LANAccessStatus>;

export function SaveMessagePushConfig(arg1:messagepush.Config):Promise<messagepush.ViewState>;

export function SaveProcessGuardSettings(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SaveRuntimeSettings(arg1:storage.RuntimeSettings):Promise<storage.RuntimeSettings>;

export function SaveTextFile(arg1:main.SaveTextFileRequest):Promise<main.SaveTextFileResult>;

export function SaveUpdateCheckPreferences(arg1:storage.UpdateCheckPreferences):Promise<storage.UpdateCheckPreferences>;

export function SaveWarehouseAutoSellSettings(arg1:storage.WarehouseAutoSellSettings):Promise<storage.WarehouseAutoSellSettings>;

export function SendMessagePushDailyTest(arg1:messagepush.Config):Promise<messagepush.SendResult>;

export function SendMessagePushTemplateTest(arg1:messagepush.Config,arg2:string,arg3:string):Promise<messagepush.SendResult>;

export function SendMessagePushTest(arg1:messagepush.Config):Promise<messagepush.SendResult>;

export function SetFarmAutomationRunMode(arg1:string):Promise<automation.State>;

export function ShowMainWindow():Promise<void>;

export function StartFarmAutomationScheduler():Promise<automation.SchedulerState>;

export function StopFarmAutomationScheduler():Promise<automation.SchedulerState>;

export function SwitchRuntimeTarget(arg1:string):Promise<runtime.Status>;

export function TSDKRuntimeEvents(arg1:number):Promise<Array<eventbus.Event>>;

export function UpdateCheckPreferences():Promise<storage.UpdateCheckPreferences>;

export function WarehouseAutoSellSettings():Promise<storage.WarehouseAutoSellSettings>;
