// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoBindHostProcess() {
  return window['go']['main']['App']['AutoBindHostProcess']();
}

export function BindHostProcess(arg1) {
  return window['go']['main']['App']['BindHostProcess'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CleanQQMiniappCache() {
  return window['go']['main']['App']['CleanQQMiniappCache']();
}

export function CleanWeChatCache() {
  return window['go']['main']['App']['CleanWeChatCache']();
}

export function CleanYYBMiniappCache() {
  return window['go']['main']['App']['CleanYYBMiniappCache']();
}

export function ClearHostBinding() {
  return window['go']['main']['App']['ClearHostBinding']();
}

export function ConfirmRuntimeAccount(arg1) {
  return window['go']['main']['App']['ConfirmRuntimeAccount'](arg1);
}

export function ConnectionInfo() {
  return window['go']['main']['App']['ConnectionInfo']();
}

export function CurrentRuntimeAccount() {
  return window['go']['main']['App']['CurrentRuntimeAccount']();
}

export function DefaultMessagePushTemplate(arg1, arg2) {
  return window['go']['main']['App']['DefaultMessagePushTemplate'](arg1, arg2);
}

export function ExitApplication() {
  return window['go']['main']['App']['ExitApplication']();
}

export function ExportRuntimeLogs(arg1) {
  return window['go']['main']['App']['ExportRuntimeLogs'](arg1);
}

export function FarmAccountStatus() {
  return window['go']['main']['App']['FarmAccountStatus']();
}

export function FarmAtlasBuyLockedCrops(arg1) {
  return window['go']['main']['App']['FarmAtlasBuyLockedCrops'](arg1);
}

export function FarmAtlasBuyLockedPreview(arg1) {
  return window['go']['main']['App']['FarmAtlasBuyLockedPreview'](arg1);
}

export function FarmAtlasPreview() {
  return window['go']['main']['App']['FarmAtlasPreview']();
}

export function FarmAutomationSchedulerState() {
  return window['go']['main']['App']['FarmAutomationSchedulerState']();
}

export function FarmAutomationState() {
  return window['go']['main']['App']['FarmAutomationState']();
}

export function FarmBackpackSeedOptions(arg1) {
  return window['go']['main']['App']['FarmBackpackSeedOptions'](arg1);
}

export function FarmCropAnalytics() {
  return window['go']['main']['App']['FarmCropAnalytics']();
}

export function FarmFeatureCatalog() {
  return window['go']['main']['App']['FarmFeatureCatalog']();
}

export function FarmFertilizeLand(arg1) {
  return window['go']['main']['App']['FarmFertilizeLand'](arg1);
}

export function FarmLandDetails() {
  return window['go']['main']['App']['FarmLandDetails']();
}

export function FarmLandDetailsSince(arg1) {
  return window['go']['main']['App']['FarmLandDetailsSince'](arg1);
}

export function FarmLandRush(arg1) {
  return window['go']['main']['App']['FarmLandRush'](arg1);
}

export function FarmMysteryShopPurchaseRecords() {
  return window['go']['main']['App']['FarmMysteryShopPurchaseRecords']();
}

export function FarmShovelLands(arg1) {
  return window['go']['main']['App']['FarmShovelLands'](arg1);
}

export function FarmSocialAction(arg1) {
  return window['go']['main']['App']['FarmSocialAction'](arg1);
}

export function FarmSocialDogGuardAction(arg1) {
  return window['go']['main']['App']['FarmSocialDogGuardAction'](arg1);
}

export function FarmSocialDogGuardState() {
  return window['go']['main']['App']['FarmSocialDogGuardState']();
}

export function FarmSocialExport(arg1) {
  return window['go']['main']['App']['FarmSocialExport'](arg1);
}

export function FarmSocialImport(arg1) {
  return window['go']['main']['App']['FarmSocialImport'](arg1);
}

export function FarmSocialProtocolBlockList(arg1) {
  return window['go']['main']['App']['FarmSocialProtocolBlockList'](arg1);
}

export function FarmSocialRankingPreferences() {
  return window['go']['main']['App']['FarmSocialRankingPreferences']();
}

export function FarmSocialRankings(arg1) {
  return window['go']['main']['App']['FarmSocialRankings'](arg1);
}

export function FarmSocialRefreshVisitors() {
  return window['go']['main']['App']['FarmSocialRefreshVisitors']();
}

export function FarmSocialState(arg1) {
  return window['go']['main']['App']['FarmSocialState'](arg1);
}

export function FarmStealCropOptions() {
  return window['go']['main']['App']['FarmStealCropOptions']();
}

export function FarmWarehouse() {
  return window['go']['main']['App']['FarmWarehouse']();
}

export function FarmWarehouseRefresh() {
  return window['go']['main']['App']['FarmWarehouseRefresh']();
}

export function FarmWarehouseSell(arg1) {
  return window['go']['main']['App']['FarmWarehouseSell'](arg1);
}

export function FarmWarehouseSellRecords(arg1) {
  return window['go']['main']['App']['FarmWarehouseSellRecords'](arg1);
}

export function FarmWorkspaceRunStatistics() {
  return window['go']['main']['App']['FarmWorkspaceRunStatistics']();
}

export function GetProgramNotice() {
  return window['go']['main']['App']['GetProgramNotice']();
}

export function GuardianStatus() {
  return window['go']['main']['App']['GuardianStatus']();
}

export function IdentifyRuntimeAccount() {
  return window['go']['main']['App']['IdentifyRuntimeAccount']();
}

export function InstallQQDebugPatch(arg1) {
  return window['go']['main']['App']['InstallQQDebugPatch'](arg1);
}

export function LANAccessSettings() {
  return window['go']['main']['App']['LANAccessSettings']();
}

export function LaunchHostProcess() {
  return window['go']['main']['App']['LaunchHostProcess']();
}

export function ListHostCandidates() {
  return window['go']['main']['App']['ListHostCandidates']();
}

export function MessagePushState() {
  return window['go']['main']['App']['MessagePushState']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function PreviewHostRestart() {
  return window['go']['main']['App']['PreviewHostRestart']();
}

export function PreviewMessagePushTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewMessagePushTemplate'](arg1, arg2, arg3);
}

export function PreviewWeChatCacheCleanup() {
  return window['go']['main']['App']['PreviewWeChatCacheCleanup']();
}

export function ProcessGuardStatus() {
  return window['go']['main']['App']['ProcessGuardStatus']();
}

export function QQDebugPatchStatus() {
  return window['go']['main']['App']['QQDebugPatchStatus']();
}

export function RestartHostProcess() {
  return window['go']['main']['App']['RestartHostProcess']();
}

export function RunDiagnostic(arg1, arg2) {
  return window['go']['main']['App']['RunDiagnostic'](arg1, arg2);
}

export function RunDueFarmAutomationTasks() {
  return window['go']['main']['App']['RunDueFarmAutomationTasks']();
}

export function RunDueMessagePushDaily() {
  return window['go']['main']['App']['RunDueMessagePushDaily']();
}

export function RunFarmAutomationTask(arg1) {
  return window['go']['main']['App']['RunFarmAutomationTask'](arg1);
}

export function RunGuardianAction(arg1) {
  return window['go']['main']['App']['RunGuardianAction'](arg1);
}

export function RunScheduledFarmAutomationTask(arg1) {
  return window['go']['main']['App']['RunScheduledFarmAutomationTask'](arg1);
}

export function RuntimeEvents(arg1) {
  return window['go']['main']['App']['RuntimeEvents'](arg1);
}

export function RuntimeLinkStatus() {
  return window['go']['main']['App']['RuntimeLinkStatus']();
}

export function RuntimeSettings() {
  return window['go']['main']['App']['RuntimeSettings']();
}

export function RuntimeStatus() {
  return window['go']['main']['App']['RuntimeStatus']();
}

export function SaveFarmAutomationState(arg1) {
  return window['go']['main']['App']['SaveFarmAutomationState'](arg1);
}

export function SaveFarmSocialRankingPreferences(arg1, arg2) {
  return window['go']['main']['App']['SaveFarmSocialRankingPreferences'](arg1, arg2);
}

export function SaveGuardianSettings(arg1) {
  return window['go']['main']['App']['SaveGuardianSettings'](arg1);
}

export function SaveLANAccessSettings(arg1) {
  return window['go']['main']['App']['SaveLANAccessSettings'](arg1);
}

export function SaveMessagePushConfig(arg1) {
  return window['go']['main']['App']['SaveMessagePushConfig'](arg1);
}

export function SaveProcessGuardSettings(arg1) {
  return window['go']['main']['App']['SaveProcessGuardSettings'](arg1);
}

export function SaveRuntimeSettings(arg1) {
  return window['go']['main']['App']['SaveRuntimeSettings'](arg1);
}

export function SaveTextFile(arg1) {
  return window['go']['main']['App']['SaveTextFile'](arg1);
}

export function SaveUpdateCheckPreferences(arg1) {
  return window['go']['main']['App']['SaveUpdateCheckPreferences'](arg1);
}

export function SaveWarehouseAutoSellSettings(arg1) {
  return window['go']['main']['App']['SaveWarehouseAutoSellSettings'](arg1);
}

export function SendMessagePushDailyTest(arg1) {
  return window['go']['main']['App']['SendMessagePushDailyTest'](arg1);
}

export function SendMessagePushTemplateTest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessagePushTemplateTest'](arg1, arg2, arg3);
}

export function SendMessagePushTest(arg1) {
  return window['go']['main']['App']['SendMessagePushTest'](arg1);
}

export function SetFarmAutomationRunMode(arg1) {
  return window['go']['main']['App']['SetFarmAutomationRunMode'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartFarmAutomationScheduler() {
  return window['go']['main']['App']['StartFarmAutomationScheduler']();
}

export function StopFarmAutomationScheduler() {
  return window['go']['main']['App']['StopFarmAutomationScheduler']();
}

export function SwitchRuntimeTarget(arg1) {
  return window['go']['main']['App']['SwitchRuntimeTarget'](arg1);
}

export function TSDKRuntimeEvents(arg1) {
  return window['go']['main']['App']['TSDKRuntimeEvents'](arg1);
}

export function UpdateCheckPreferences() {
  return window['go']['main']['App']['UpdateCheckPreferences']();
}

export function WarehouseAutoSellSettings() {
  return window['go']['main']['App']['WarehouseAutoSellSettings']();
}
